export const INTERVIEWPROCESS_DELETE_FAIL = "INTERVIEWPROCESS_DELETE_FAIL";
export const INTERVIEWPROCESS_DELETE_REQUEST =
  "INTERVIEWPROCESS_DELETE_REQUEST";
export const INTERVIEWPROCESS_DELETE_SUCCESS =
  "INTERVIEWPROCESS_DELETE_SUCCESS";
export const INTERVIEWPROCESS_LIST_FAIL = "INTERVIEWPROCESS_LIST_FAIL";
export const INTERVIEWPROCESS_LIST_REQUEST = "INTERVIEWPROCESS_LIST_REQUEST";
export const INTERVIEWPROCESS_LIST_SUCCESS = "INTERVIEWPROCESS_LIST_SUCCESS";
export const INTERVIEWPROCESS_SAVE_FAIL = "INTERVIEWPROCESS_SAVE_FAIL";
export const INTERVIEWPROCESS_SAVE_REQUEST = "INTERVIEWPROCESS_SAVE_REQUEST";
export const INTERVIEWPROCESS_SAVE_SUCCESS = "INTERVIEWPROCESS_SAVE_SUCCESS";
